python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":34,"dropout":0.2,"etp_fusion_alpha":0.95,"hidden_dim":4096,"horizon":24,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":168,"sfta_ratio":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":180,"dropout":0.7,"etp_fusion_alpha":0.95,"hidden_dim":256,"horizon":360,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":720,"sfta_ratio":0.55}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":24,"dropout":0.3,"etp_fusion_alpha":0.25,"hidden_dim":512,"horizon":24,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type1","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":168,"sfta_ratio":0.05}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":360,"dropout":0.2,"etp_fusion_alpha":0.45,"hidden_dim":128,"horizon":360,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type1","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":720,"sfta_ratio":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.05,"scfm_hidden_dim":512,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":96,"dropout":0.0,"etp_fusion_alpha":0.525,"hidden_dim":2048,"horizon":24,"individual":0,"loss":"MAE","lr":0.0001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":168,"sfta_ratio":1.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":180,"dropout":0.85,"etp_fusion_alpha":0.95,"hidden_dim":384,"horizon":360,"individual":0,"loss":"MAE","lr":0.0001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":720,"sfta_ratio":1.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.3,"scfm_hidden_dim":2048,"scfm_state_hidden_dim":1024,"scfm_num_layers":1,"scfm_state_len":96,"dropout":0.05,"etp_fusion_alpha":0.35,"hidden_dim":2048,"horizon":24,"individual":0,"loss":"MAE","lr":0.0001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":168,"sfta_ratio":0.1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":576,"dropout":0.9,"etp_fusion_alpha":0.95,"hidden_dim":384,"horizon":360,"individual":0,"loss":"MAE","lr":0.0001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":720,"sfta_ratio":1.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":1024,"scfm_state_hidden_dim":1024,"scfm_num_layers":2,"scfm_state_len":168,"dropout":0.2,"etp_fusion_alpha":0.325,"hidden_dim":1024,"horizon":24,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":168,"sfta_ratio":0.6}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.05,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":180,"dropout":0.8,"etp_fusion_alpha":0.55,"hidden_dim":24,"horizon":360,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":720,"sfta_ratio":0.25}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":96,"dropout":0.2,"etp_fusion_alpha":0.2,"hidden_dim":256,"horizon":24,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type1","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":168,"sfta_ratio":0.5}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":90,"dropout":0.1,"etp_fusion_alpha":0.65,"hidden_dim":4096,"horizon":360,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type1","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":720,"sfta_ratio":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":128,"scfm_state_hidden_dim":128,"scfm_num_layers":2,"scfm_state_len":0,"dropout":0,"etp_fusion_alpha":0,"hidden_dim":2048,"horizon":24,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":168,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":128,"scfm_state_hidden_dim":128,"scfm_num_layers":2,"scfm_state_len":0,"dropout":0.01,"etp_fusion_alpha":0,"hidden_dim":256,"horizon":360,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":720,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":128,"scfm_state_hidden_dim":128,"scfm_num_layers":2,"scfm_state_len":0,"dropout":0.01,"etp_fusion_alpha":0,"hidden_dim":4096,"horizon":24,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":168,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":128,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":0,"dropout":0.01,"etp_fusion_alpha":0,"hidden_dim":2048,"horizon":360,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":720,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":128,"scfm_state_hidden_dim":128,"scfm_num_layers":2,"scfm_state_len":0,"dropout":0.9,"etp_fusion_alpha":0.6,"hidden_dim":512,"horizon":24,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":168,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":128,"scfm_state_hidden_dim":128,"scfm_num_layers":2,"scfm_state_len":0,"dropout":0,"etp_fusion_alpha":0,"hidden_dim":128,"horizon":360,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":720,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":64,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":0,"dropout":0.9,"etp_fusion_alpha":0.15,"hidden_dim":128,"horizon":24,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":168,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/FuExoMLP/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":128,"scfm_state_hidden_dim":128,"scfm_num_layers":2,"scfm_state_len":0,"dropout":0,"etp_fusion_alpha":0,"hidden_dim":128,"horizon":360,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":720,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/FuExoMLP/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon":10,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":60,"dropout":0,"etp_fusion_alpha":0,"hidden_dim":512,"horizon":10,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":60,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/FuExoMLP/h10" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon":30,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":60,"dropout":0.9,"etp_fusion_alpha":0.05,"hidden_dim":128,"horizon":30,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":180,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/FuExoMLP/h30" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon":10,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":20,"dropout":0,"etp_fusion_alpha":0.2,"hidden_dim":2048,"horizon":10,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":2,"patience":5,"seq_len":60,"sfta_ratio":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/FuExoMLP/h10" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon":30,"target_channel":[-1]}' --model-name "fuexomlp.FuExoMLP" --model-hyper-params '{"batch_size":64,"scfm_dropout":0.1,"scfm_hidden_dim":256,"scfm_state_hidden_dim":256,"scfm_num_layers":2,"scfm_state_len":120,"dropout":0.6,"etp_fusion_alpha":0.35,"hidden_dim":256,"horizon":30,"individual":0,"loss":"MAE","lr":0.001,"lradj":"type3","model_variant":"fuexomlp","norm":true,"num_epochs":50,"num_layers":1,"patience":5,"seq_len":180,"sfta_ratio":0.3}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/FuExoMLP/h30" --deterministic full
