python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":16,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":1536,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":16,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":512,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":16,"d_model":128,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":1024,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":12,"d_model":128,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":64,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":8,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":1024,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":16,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":1024,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":8,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":1024,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":16,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":512,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":16,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":512,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":12,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":32,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":40,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":128,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":30,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":2048,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":36,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":1024,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":24,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":2048,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":12,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":1e-05,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":1024,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":24,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":1e-05,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":2048,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":48,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":1e-05,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":512,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":48,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":1e-05,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":128,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":48,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":24,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"t_dropout":0.0,"t_ff":512,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/XLinear/h24" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":48,"d_model":256,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":360,"loss":"MSE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"t_dropout":0.0,"t_ff":512,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/XLinear/h360" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon":10,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":12,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":10,"loss":"MSE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":60,"t_dropout":0.0,"t_ff":512,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/XLinear/h10" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon":30,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":12,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":30,"loss":"MSE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":180,"t_dropout":0.0,"t_ff":256,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/XLinear/h30" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon":10,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":16,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":10,"loss":"MSE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":60,"t_dropout":0.0,"t_ff":1024,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/XLinear/h10" --deterministic full

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon":30,"target_channel":[-1]}' --model-name "xlinear.XLinear" --model-hyper-params '{"batch_size":16,"c_dropout":0.0,"c_ff":8,"d_model":64,"embed_dropout":0.0,"features":"MS","fusion_method":"mlp","head_dropout":0.0,"horizon":30,"loss":"MSE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":180,"t_dropout":0.0,"t_ff":256,"usenorm":true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/XLinear/h30" --deterministic full
